name = "unixtime-app-refs"
type = "javascript"

account_id = "78531bcccbdf82e16d60a37a4857f859"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "REFS", id = "47167420204843deb816f1a2e714ff39", preview_id = "da89d3f0e6b746a59dd66c114bc059e8"  },
]
compatibility_date = "2022-07-26"
