on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get install nodejs yarn
      - name: Build
        run: |
          yarn && make build-parcel-for-web

      - name: Publish Page
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: unixtime-app # e.g. 'my-project'
          directory: dist-parcel # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'worker'
          command: publish index.js --name unixtime-app-refs

