on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get install nodejs yarn
      - name: Build
        run: |
          yarn && yarn run parcel build src/index.html --public-url . --dist-dir dist-parcel
      - name: Publish
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: unixtime-app # e.g. 'my-project'
          directory: dist-parcel # e.g. 'dist'
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
