on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Deploy to Cloudflare
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          sudo apt-get install nodejs yarn
      - name: Build
        run: |
          yarn && make magic

      - name: Publish Page
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: unixtime-app
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
